version: 2

workflows:
  version: 2
  default:
    jobs:
      - build
      - release
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: mbgl/android-ndk-r19:8e91a7ebab
    environment:
      JVM_OPTS: -Xmx3200m
      BUILDTYPE: Debug
      IS_LOCAL_DEVELOPMENT: false
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Check code style
          command: make checkstyle
      - run:
          name: Run Lint
          command: ./gradlew lint
      - run:
          name: Run unit-test in Android libraries
          command: make test
      - run:
          name: Log in to Google Cloud Platform
          shell: /bin/bash -euo pipefail
          command: |
            echo "${GCLOUD_SERVICE_ACCOUNT_JSON}" > secret.json
            gcloud auth activate-service-account --key-file secret.json --project mapbox-events-android
            rm secret.json
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results

# ------------------------------------------------------------------------------
  release:
    branch:
      only:
      - master
    docker:
      - image: mbgl/android-ndk-r19:8e91a7ebab
    working_directory: ~/code
    environment:
      BUILDTYPE: Release
      IS_LOCAL_DEVELOPMENT: false
    steps:
      - checkout
      - run:
          name: Generate Bintray credentials
          shell: /bin/bash -euo pipefail
          command: |
            if [ -n "${BINTRAY_USER}" ]; then
              echo "BINTRAY_USER=$BINTRAY_USER
              BINTRAY_API_KEY=$BINTRAY_API_KEY
              GPG_PASSPHRASE=$GPG_PASSPHRASE"
            fi
      - run:
          name: Update version name
          command: |
            if [[ $CIRCLE_TAG == v* ]]; then
              sed -i -e "s/^VERSION_NAME=.*/VERSION_NAME=${CIRCLE_TAG:9}/" library/gradle.properties
            fi      
      - run:
          name: Build libraries
          command: make release
      - deploy:
          name: Publish to Bintray
          command: |
            if [[ $CIRCLE_BRANCH == master ]] || [[ $CIRCLE_TAG == v* ]]; then
              version=$(cat library/gradle.properties | grep "VERSION_NAME")
              if [[ $version != *"SNAPSHOT"* ]]; then
                make publish-stable
              else
                make publish-snapshot-to-artifactory
              fi
            fi
      - store_artifacts:
          path: app/build/reports
          destination: reports