name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mbgl/android-sdk:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check code style
        run: make checkstyle

      - name: Run Lint
        run: ./gradlew lint

      - name: Run unit-test in Android libraries
        run: make test

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: app/build/reports

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: app/build/test-results

#  release:
#    runs-on: ubuntu-latest
#    container:
#      image: mbgl/android-ndk-r21e:latest
#    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v'))
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Init aws with mbx-ci
#        run: |
#          curl -Ls https://mapbox-release-engineering.s3.amazonaws.com/mbx-ci/latest/mbx-ci-linux-amd64 > mbx-ci && chmod 755 ./mbx-ci
#          ./mbx-ci aws setup
#
#      - name: Update version name
#        run: |
#          if [[ $GITHUB_REF == refs/tags/v* ]]; then
#            VERSION_NAME=${GITHUB_REF#refs/tags/v}
#            sed -i -e "s/^VERSION_NAME=.*/VERSION_NAME=${VERSION_NAME}/" library/gradle.properties
#          elif [[ $GITHUB_REF == refs/heads/master ]]; then
#            COMMIT_SHA=$(git rev-parse --short HEAD)
#            sed -i -e "s/-SNAPSHOT.*/-${COMMIT_SHA}-SNAPSHOT/" library/gradle.properties
#          fi
#
#      - name: Build libraries
#        run: make release
#
#      - name: Publish to the SDK registry
#        env:
#          GITHUB_TOKEN: ${{ secrets.SDK_REGISTRY_TOKEN }}
#        run: |
#          git config --global user.email "MapboxCI@users.noreply.github.com"
#          git config --global user.name "MapboxCI"
#          if [[ $GITHUB_REF == refs/heads/master ]] || [[ $GITHUB_REF == refs/tags/v* ]]; then
#            make sdkRegistryUpload
#          fi
#          if [[ $GITHUB_REF == refs/tags/v* ]]; then
#            make sdkRegistryPublish
#          fi