name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mbgl/android-sdk:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check code style
        run: make checkstyle

      - name: Run Lint
        run: ./gradlew lint

      - name: Run unit-test in Android libraries
        run: make test

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: app/build/reports

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: app/build/test-results